trigger:
- master

steps:
- task: Docker@2
  displayName: Build an image
  inputs: 
    command: build
    Dockerfile: Dockerfile
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'